# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'text', 'label', 'anime', 'movie', 'examples', 'title', 'description', 'intf', 'classify_text']

# %% app.ipynb 2
from fastai.vision.all import *
import gradio as gr

# %% app.ipynb 4
learn = load_learner('model.pkl')

# %% app.ipynb 7
categories = ('Anime', 'Movie')

def classify_text(text):
    pred,idx,probs = learn.predict(text)
    return dict(zip(categories, map(float,probs)))

# %% app.ipynb 10
text = gr.TextArea()
label = gr.outputs.Label()

anime = "After the betrayal of his companions, Haruyoshi, the strongest diviner, was on the verge of dying. Hoping to be happy in the next life, he attempted the secret reincarnation technique and was sent to a different world! Born into a family of magicians, the magic he didn't inherit paled in comparison to his previous abilities as an onmyouji. 'Who needs magic? I'll survive in this world with my old techniques!'"
movie = "During World War I, a father enlists himself in the French Army in order to be with his 17-year-old son who was recruited against his will. Sent to the front, they find themselves facing the war together in the French colony of Senegal."

examples = [anime, movie]

title = "Synopsis Text Recognition"
description = "<p style='text-align: center'>Identifier si un synopsis provient d'un anime ou un film.</p>"

intf = gr.Interface(fn=classify_text, title=title, description=description, inputs=text, outputs=label, examples=examples)
intf.launch(inline=False, debug = 'True')
